services:
  mysql:
    image: 'mysql'
    ports:
      - "3307:3306"
    expose:
      - "3307"
    container_name: 'picpaydb'
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=picpaydb
      - MYSQL_ROOT_PASSWORD=123
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
